// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLOmUhaHrCQjKZ94nWg-FXw-D8T2yMW8',
    appId: '1:127316575856:web:8581e222973f04e2a356b5',
    messagingSenderId: '127316575856',
    projectId: 'smart-meal-ce145',
    authDomain: 'smart-meal-ce145.firebaseapp.com',
    storageBucket: 'smart-meal-ce145.firebasestorage.app',
    measurementId: 'G-LQ7BKXGHS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvCkG-lkhqPoyrqob_gc5YD3FfB3fW_o',
    appId: '1:127316575856:android:e567e5ae03d3694ea356b5',
    messagingSenderId: '127316575856',
    projectId: 'smart-meal-ce145',
    storageBucket: 'smart-meal-ce145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALkCRlK2SYhVYxJuSc5XOfO9yh_YSy3BI',
    appId: '1:127316575856:ios:f03d05ed981474cca356b5',
    messagingSenderId: '127316575856',
    projectId: 'smart-meal-ce145',
    storageBucket: 'smart-meal-ce145.firebasestorage.app',
    iosBundleId: 'com.example.smartMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALkCRlK2SYhVYxJuSc5XOfO9yh_YSy3BI',
    appId: '1:127316575856:ios:f03d05ed981474cca356b5',
    messagingSenderId: '127316575856',
    projectId: 'smart-meal-ce145',
    storageBucket: 'smart-meal-ce145.firebasestorage.app',
    iosBundleId: 'com.example.smartMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVLOmUhaHrCQjKZ94nWg-FXw-D8T2yMW8',
    appId: '1:127316575856:web:29d85976a1146ac7a356b5',
    messagingSenderId: '127316575856',
    projectId: 'smart-meal-ce145',
    authDomain: 'smart-meal-ce145.firebaseapp.com',
    storageBucket: 'smart-meal-ce145.firebasestorage.app',
    measurementId: 'G-C05SP9X45V',
  );
}
